[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
trading_bot = "497cyv12aNpr31KHVJYbRJot1QhpEiVohb2h4zkb4NZh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/jGiW2kM8P4SSDUlQRTTg1gsCHq-wq5bm"
wallet = "~/.config/solana/id.json"
tx_timeout = 120_000

[test]
log = true


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
